### ISSUE TITLE
【来访】页中的【查看】tab页无数据；别人发的闪照只提示闪照消息而不展示图片

### ISSUE THREAD

**Issue by lyxcool** [CoolBreezeArcanine/fxxk-13lued#1]

**Comment by CoolBreezeArcanine** [comment]
来访里的查看是由于广告过滤导致的，正在处理中。
如果对方发来的闪照客户端是iOS，则查看会有bug，目前已定位到问题，稍晚时候发布针对此bug的修复。

**Comment by CoolBreezeArcanine** [comment]
> 安卓发过来的闪照也看不了，发过来的版本是7.21.6……

Android部分版本发过来的没这个问题，玄学，但bug位置都是同一个，等我晚上修复吧

**Comment by CoolBreezeArcanine** [comment]
已修复。
