### ISSUE TITLE
【访客】页面的【查看】选项卡显示空白

### ISSUE THREAD

**Issue by ec-to** [CoolBreezeArcanine/fxxk-13lued#2]
希望加入一些功能开关，"我的"页面，无法进入会员中心，访问页也空白了。
![1000083827](https://github.com/user-attachments/assets/42ad7a16-bdb5-4776-882f-0442bdb44c0a)

**Comment by CoolBreezeArcanine** [comment]
【访问】页展示空白的问题为广告过滤引起，由于该列表数据处理的方法引用了一个广告配置，导致列表最后返回为空，需要特殊处理，已着手处理。

关于开关设置的问题，目前的写法是直接做到【设置】页面然后新增一个条目，点进去即可配置，但具体的实现还在研究，目前面向的群体是没开会员的群体，故先暂时选择了劫持VIP版块；如你有需要进入VIP版块查看的需求可以先暂时禁用模块。

**Comment by CoolBreezeArcanine** [comment]
页面空白的问题已修复，新增开关的提议我会单独开一个issue。
