### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by serendipity091** [CoolBreezeArcanine/fxxk-13lued#5]
大佬，可以解锁隐藏距离与隐藏时间吗，就是直接就显示出来真实的距离与在线时间了

**Comment by ec-to** [comment]
不行，那是服务器端做的限制了，根本不会显示手机上再隐藏。

**Comment by CoolBreezeArcanine** [comment]
![image](https://github.com/user-attachments/assets/2a7b0c0b-3fe4-4886-8fe8-647f9f3b7c4e)
无法实现，服务端的返回信息做了限制。

**Comment by serendipity091** [comment]
> ![image](https://private-user-images.githubusercontent.com/80762104/384720580-2a7b0c0b-3fe4-4886-8fe8-647f9f3b7c4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyOTQ3NjQsIm5iZiI6MTczMTI5NDQ2NCwicGF0aCI6Ii84MDc2MjEwNC8zODQ3MjA1ODAtMmE3YjBjMGItM2ZlNC00ODg2LThmZTgtNjQ3ZjlmM2I3YzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDAzMDc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMDM2NWQyZGIzNzRmMjk3OGJlZDJjNjU1MjM2NDI3NjY3NTk2Y2UwZGM4OGY5NGY4NDNjMmEwZDIwODJiMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lwXXL8ZmMr-KQw8sa8CvcEN3J1pZ7XLLIgFbAB2XLFE) 无法实现，服务端的返回信息做了限制。

大佬，可是我用的苹果插件就实现了，就打开个人主页慢慢就直接显示出来了。大佬需不需要参考一下他们的，电报二维码如下
![Uploading Screenshot_2024-11-11-11-11-53-34_362d562e1c1f3d306edda8d1e97eb696.jpg…]()
上

**Comment by serendipity091** [comment]
> 不行，那是服务器端做的限制了，根本不会显示手机上再隐藏。

可以的，我苹果上插件就可以有这个功能
