### ISSUE TITLE
建议2.0

### ISSUE THREAD

**Issue by serendipity091** [CoolBreezeArcanine/fxxk-13lued#6]

**Comment by serendipity091** [comment]
大佬，这是他们的更新内容，大佬可以参考一下。



#!name=blued增强脚本已完善--Eric全网独发，转载请注明出处,免费分享禁止转卖
#!desc=查看会员隐藏距离，查看会员保密的最后在线时间，地图找人次数到期，地图显示头像和影子功能，捕获闪照视频,全球随意修改定位(需使用boxjs可自定义修改参数)等功能
#重点使用说明:所有功能均需要使用boxjs进行密码验证，否则无法使用所有功能，boxjs需填写密码和开启脚本填写true，禁用脚本填写false保存即可无需运行，仅支持surge、loon；模块删除了全部ip解析功能，如若规则失效手动自行添加mitm:surge添加<ip-address>，loon添加*即可，不使用时禁用，避免影响其他APP使用
#更新说明:2024-07-09可查看会员模糊真实头像功能;使用https://jingweidu.bmcx.com可查看具体位置的经纬度；感谢@ios151大佬提供更新自定义修改经纬度坐标需使用boxjs工具添加修改经纬度坐标或直接修改城市二选一即可
#更新说明:2024-07-10更新闪照、视频捕获功能防止销毁或撤回，07-21新增日志输出，链接可通过日志查看避免通知栏跳转后丢失
#更新说明:2024-07-12更新附近的群组定位功能，更新具体保密位置和最后上线时间
#更新说明:2024-07-16新增全局悄悄查看对方消息，只要不回复对方消息，对方聊天框只显示未读
#更新说明:2024-07-18新增单独脚本可使用boxjs控制脚本启用和禁用功能，默认开启全部脚本，输入密码后开启脚本后保存即可无须点击运行
#更新说明:2024-07-19更新翻咔定位功能及附近的人查看头像
#更新说明:2024-07-20更新Hornet定位功能
#更新说明:2024-07-28修复影子头像查看功能，新增地图找人无限使用次数。
#更新说明:2024-08-03增加好友聊天页面消息气泡随机功能
#频道获取密码https://t.me/+2T-oJk2FFts4NDZl，群组聊天https://t.me/+A1cOYwvOdeI4MWNl
#更新说明：Blued交友软件修复低版本限制登录及闪照功能问题，任何低版本随意登录无限制版本，此脚本支持普通版最新版7.31.6：
https://raw.githubusercontent.com/Alex0510/Eric/master/surge/Module/blued.sgmodule


#surge使用：
#1.添加surge_boxjs地址：https://raw.githubusercontent.com/chavyleung/scripts/master/box/rewrite/boxjs.rewrite.surge.sgmodule
#2.添加surge_blued地址：https://raw.githubusercontent.com/Alex0510/Eric/master/surge/Module/blued.sgmodule
#3.以上模块添加完毕后使用浏览器打开http://www.boxjs.com添加boxjs订阅地址:https://raw.githubusercontent.com/Alex0510/Eric/master/surge/Script/blued.box.json，订阅后在boxjs里输入密码和开启脚本保存即可，无需点击运行(开启为true；禁用为false)
#4.必须手动在surge的mitm里添加<ip-address>进行解析,不使用时禁用，避免影响其他APP使用。

#loon使用
#1.添加loon_boxjs地址：https://raw.githubusercontent.com/chavyleung/scripts/master/box/rewrite/boxjs.rewrite.loon.plugin
#2.添加loon插件转换地址：https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/modules/script-hub.beta.loon.plugin
#3.以上模块添加完毕后使用浏览器打开http://www.boxjs.com添加boxjs订阅地址:https://raw.githubusercontent.com/Alex0510/Eric/master/surge/Script/blued.box.json,订阅后在boxjs里输入密码和开启脚本保存即可，无需点击运行(开启为true；禁用为false)
#4.loon需使用插件进行转换模块需使用浏览器打开script.hub,模块地址:https://raw.githubusercontent.com/Alex0510/Eric/master/surge/Module/blued.sgmodule按页面提示操作进行转换，将转换后的插件地址添加到loon插件；
#5.必须手动在mitm里添加*进行解析，不使用时禁用，避免影响其他APP使用。

**Comment by CoolBreezeArcanine** [comment]
这个js被加密过了，不具有参考价值。
如果你能弄清楚原理，要复刻就很容易。

**Comment by PzHown** [comment]
> 这个js被加密过了，不具有参考价值。 如果你能弄清楚原理，要复刻就很容易。

太牛了，老师
